name: Deploy to DigitalOcean

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: 22
          script: |
            cd brollyjuniors.site
            cd brollyjuniors
            chmod +x deploy.sh
            ./deploy.sh
